use_frameworks!

target 'MJReachability_Example', :exclusive => true do
  pod 'MJReachability', :path => '../'
end

target 'MJReachability_Tests', :exclusive => true do
  pod 'MJReachability', :path => '../'

  
end
